"""
Question model for Socratic questioning workflow.
"""
from sqlalchemy import Column, String, Text, Numeric, ForeignKey, Index
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import relationship

from .base import BaseModel


class Question(BaseModel):
    """
    Question model - stores questions generated by SocraticCounselorAgent.
    Stored in socrates_specs database.

    Fields:
    - id: UUID (inherited from BaseModel)
    - project_id: Foreign key to projects table
    - session_id: Foreign key to sessions table
    - text: The actual question text
    - category: Question category (goals, requirements, tech_stack, etc.)
    - context: Explanation of why this question matters
    - quality_score: Quality score from QualityControllerAgent (0.00-1.00)
    - created_at: Timestamp (inherited from BaseModel)
    - updated_at: Timestamp (inherited from BaseModel)
    """
    __tablename__ = "questions"
    __table_args__ = (
        Index('idx_questions_project_id', 'project_id'),
        Index('idx_questions_session_id', 'session_id'),
        Index('idx_questions_category', 'category'),
        Index('idx_questions_created_at', 'created_at'),
    )

    project_id = Column(
        PG_UUID(as_uuid=True),
        ForeignKey('projects.id', ondelete='CASCADE'),
        nullable=False,
        comment="Foreign key to projects table"
    )

    session_id = Column(
        PG_UUID(as_uuid=True),
        ForeignKey('sessions.id', ondelete='CASCADE'),
        nullable=False,
        comment="Foreign key to sessions table"
    )

    text = Column(
        Text,
        nullable=False,
        comment="The actual question text"
    )

    category = Column(
        String(50),
        nullable=False,
        comment="Question category: goals, requirements, tech_stack, scalability, security, performance, testing, monitoring, data_retention, disaster_recovery"
    )

    context = Column(
        Text,
        nullable=True,
        comment="Explanation of why this question is important"
    )

    quality_score = Column(
        Numeric(3, 2),
        nullable=False,
        default=1.0,
        server_default='1.0',
        comment="Quality score from QualityControllerAgent (0.00-1.00)"
    )

    # Relationships
    project = relationship("Project", back_populates="questions")
    session = relationship("Session", back_populates="questions")

    def __repr__(self):
        """String representation of question"""
        return f"<Question(id={self.id}, category={self.category}, text='{self.text[:50]}...')>"
